require("core.plugin_config.nerdtree")
require("core.plugin_config.colorschema")
require("core.plugin_config.lualine")
require("core.plugin_config.lsp-config")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.trouble")
require("core.plugin_config.commenting")
